### ISSUE TITLE
Elaborate on the change of private key bytes?

### ISSUE THREAD

**Issue by tisba** [charmbracelet/melt#41]
This is a fascinating tool, thank you 💕 

I was wondering, if you could elaborate (or link to further resource), explaining this caveat from the README:

> Some bytes of your private key might change, due to their random block. The key is effectively the same though.

Is that a general property of ED25519 private keys? Or just the storage format? I'm curious.

**Comment by caarlos0** [comment]
hey @tisba! 

ah yes! 

Ok, first, the way go marshals the private key isn't the same, you'd get different line lengths... that's the first difference, which we could get around, but it doesn't really matter, as the key is still valid.

The second difference is due to how openssh private keys are marshaled: there's block of 2 repeated, but random, numbers. 

That does not change the actual key "secret", which is why their public keys are the same and also why the private key's fingerprint are the same (`ssh-keygen -l -f path`).


#### 2 numbers

The openssh private key format has 2 "checksum numbers" (the "64-bit dummy checksum?  # a random 32-bit int, repeated" field[^1]), which you can see we set in [here](https://github.com/caarlos0/sshmarshal/blob/b3ea5af284efd0f575718960859d15595fcb10f9/marshal.go#LL131-L138)... so that's what's different.

[^1]: https://coolaj86.com/articles/the-openssh-private-key-format/


---

Hopefully that clarifies things! Let me know if you still have any questions.

**Comment by caarlos0** [comment]
I also wrote this: https://charm.sh/blog/ssh-key-marshal/

all that said, closing this issue now :)
